name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '**/*.md'
jobs:
  markdown-lint:
    name: Lint markdown files
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        if: ${{ !github.event.repository.private }}
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Register markdownlint warning matcher
        run: |
          echo "::add-matcher::.github/markdownlint.json"

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: '**/*.md'
          ignore: '**/testinput/**'
          config: '.github/markdownlint.jsonc'

      - name: Remove markdownlint warning matcher
        if: always()
        run: |
          echo "::remove-matcher owner=markdownlint::"

  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devtools
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        # checks all markdown files from /docs including all subfolders
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/markdown-link-check.jsonc'
